New version 1.2. Added config files to installer. Added check for 7zip.

diff --git a/installer b/installer
--- a/installer
+++ b/installer
@@ -2,22 +2,21 @@
 /**
  * @file
  * Backup CLI installer.
- * Based on platform.sh CLI installer.
  */
 
 define('MANIFEST_URL', 'https://fabioneves.github.io/backup-cli/manifest.json');
 $pharFilename = 'backup-cli.phar';
 
 set_error_handler(
-    function ($code, $message) {
-        if ($code & error_reporting()) {
-            echo PHP_EOL . "Error ($code): $message" . PHP_EOL;
-            exit(1);
-        }
-    }
+  function ($code, $message) {
+      if ($code & error_reporting()) {
+          echo PHP_EOL . "Error ($code): $message" . PHP_EOL;
+          exit(1);
+      }
+  }
 );
 
-output("Backup CLI installer", 'heading');
+output("\nBackup CLI installer", 'heading');
 
 // Run environment checks.
 output(PHP_EOL . "Environment check", 'heading');
@@ -25,70 +24,80 @@ output(PHP_EOL . "Environment check", 'heading');
 // Check the PHP version.
 $min_php = '5.5.9';
 check(
-    sprintf('The PHP version is supported: %s.', PHP_VERSION),
-    sprintf('The PHP version is %s, but %s or greater is required.', PHP_VERSION, $min_php),
-    function () use ($min_php) {
-        return version_compare(PHP_VERSION, $min_php, '>=');
-    }
+  sprintf('The PHP version is supported: %s.', PHP_VERSION),
+  sprintf('The PHP version is %s, but %s or greater is required.', PHP_VERSION, $min_php),
+  function () use ($min_php) {
+      return version_compare(PHP_VERSION, $min_php, '>=');
+  }
 );
 
 // Check that the openssl extension exists.
 check(
-    'The "openssl" PHP extension is installed.',
-    'Warning: the "openssl" PHP extension will be needed.',
-    function () {
-        return extension_loaded('openssl');
-    },
-    false
+  'The "openssl" PHP extension is installed.',
+  'Warning: the "openssl" PHP extension will be needed.',
+  function () {
+      return extension_loaded('openssl');
+  },
+  false
 );
 
 // Check that the curl extension exists.
 check(
-    'The "curl" PHP extension is installed.',
-    'Warning: the "curl" PHP extension will be needed.',
-    function () {
-        return extension_loaded('curl');
-    },
-    false
+  'The "curl" PHP extension is installed.',
+  'Warning: the "curl" PHP extension will be needed.',
+  function () {
+      return extension_loaded('curl');
+  },
+  false
 );
 
 // Check Suhosin restrictions.
 if (extension_loaded('suhosin')) {
     check(
-        'The "phar" stream wrapper is allowed by Suhosin.',
-        'The "phar" stream wrapper is blocked by Suhosin.',
-        function () {
-            $white = ini_get('suhosin.executor.include.whitelist');
-            $black = ini_get('suhosin.executor.include.blacklist');
+      'The "phar" stream wrapper is allowed by Suhosin.',
+      'The "phar" stream wrapper is blocked by Suhosin.',
+      function () {
+          $white = ini_get('suhosin.executor.include.whitelist');
+          $black = ini_get('suhosin.executor.include.blacklist');
 
-            if ((false === stripos($white, 'phar'))
-                || (false !== stripos($black, 'phar'))
-            ) {
-                return false;
-            }
+          if ((false === stripos($white, 'phar'))
+            || (false !== stripos($black, 'phar'))
+          ) {
+              return false;
+          }
 
-            return true;
-        }
+          return true;
+      }
     );
 }
 
 // Check whether PHP can open files via URLs.
 check(
-    'The "allow_url_fopen" setting is on.',
-    'The "allow_url_fopen" setting is off; it must be on.',
-    function () {
-        return (true == ini_get('allow_url_fopen'));
-    }
+  'The "allow_url_fopen" setting is on.',
+  'The "allow_url_fopen" setting is off; it must be on.',
+  function () {
+      return (true == ini_get('allow_url_fopen'));
+  }
 );
 
 // Check a troublesome APC setting.
 check(
-    'The "apc.enable_cli" setting is off.',
-    'Warning: the "apc.enable_cli" is on; this may cause problems with Phar files.',
-    function () {
-        return (false == ini_get('apc.enable_cli'));
-    },
-    false
+  'The "apc.enable_cli" setting is off.',
+  'Warning: the "apc.enable_cli" is on; this may cause problems with Phar files.',
+  function () {
+      return (false == ini_get('apc.enable_cli'));
+  },
+  false
+);
+
+// Check if 7zip is installed.
+check(
+  '7zip is installed (7za).',
+  '7zip is not installed, please install it first.',
+  function () {
+      return (`which 7za`);
+  },
+  true
 );
 
 // The necessary checks have passed. Start downloading the right version.
@@ -121,7 +130,7 @@ if (empty($latest)) {
 }
 
 output("  Downloading version {$latest->version}...");
-if (!file_put_contents($pharFilename, file_get_contents($latest->url))) {
+if (!file_put_contents($pharFilename, file_get_contents($latest->url . $pharFilename))) {
     output("  The download failed.", 'error');
 }
 
@@ -146,9 +155,26 @@ output("  Making the Phar executable...");
 chmod($pharFilename, 0755);
 $executable = $pharFilename;
 
+// Create config folder and files.
+if (!file_exists('config')) {
+    mkdir('config', 0755);
+}
+if (!file_put_contents('config/database.yml', file_get_contents($latest->url . 'config/database.yml'))) {
+    output("  Failed to download database.yml config file.", 'error');
+}
+if (!file_put_contents('config/storage.yml', file_get_contents($latest->url . 'config/storage.yml'))) {
+    output("  Failed to download storage.yml config file.", 'error');
+}
+
+// Create symlink 'backup-cli'
+if (!file_exists('/usr/local/bin/backup-cli')) {
+    output("  Creating a symlink `backup-cli` in /usr/local/bin...");
+    symlink(getcwd() . '/' . $pharFilename, '/usr/local/bin/backup-cli');
+}
+
 output(
-    PHP_EOL . "The Backup CLI v{$latest->version} was installed successfully!",
-    'success'
+  PHP_EOL . "Backup CLI v{$latest->version} was installed successfully!\n",
+  'success'
 );
 
 /**
@@ -192,17 +218,17 @@ function output($text, $color = null, $newLine = true)
             // On Windows, default to no ANSI, except in ANSICON and ConEmu.
             // Everywhere else, default to ANSI if stdout is a terminal.
             $ansi = (DIRECTORY_SEPARATOR == '\\')
-                ? (false !== getenv('ANSICON') || 'ON' === getenv('ConEmuANSI'))
-                : (function_exists('posix_isatty') && posix_isatty(1));
+              ? (false !== getenv('ANSICON') || 'ON' === getenv('ConEmuANSI'))
+              : (function_exists('posix_isatty') && posix_isatty(1));
         }
     }
 
     static $styles = array(
-        'success' => "\033[0;32m%s\033[0m",
-        'error' => "\033[31;31m%s\033[0m",
-        'info' => "\033[33m%s\033[39m",
-        'warning' => "\033[33m%s\033[39m",
-        'heading' => "\033[1;33m%s\033[22;39m",
+      'success' => "\033[0;32m%s\033[0m",
+      'error'   => "\033[31;31m%s\033[0m",
+      'info'    => "\033[33m%s\033[39m",
+      'warning' => "\033[33m%s\033[39m",
+      'heading' => "\033[1;33m%s\033[22;39m",
     );
 
     $format = '%s';
